import api from '../../../api/client';
export const adminApi = {
  customers: (params) => api.get('/api/admin/customers', params),
  createCustomer: (data) => api.post('/api/admin/customers', data),
  updateCustomer: (id, data) => api.put(`/api/admin/customers/${id}`, data),
  deleteCustomer: (id) => api.delete(`/api/admin/customers/${id}`),
  suppliers: (params) => api.get('/api/admin/suppliers', params),
  createSupplier: (data) => api.post('/api/admin/suppliers', data),
  updateSupplier: (id, data) => api.put(`/api/admin/suppliers/${id}`, data),
  deleteSupplier: (id) => api.delete(`/api/admin/suppliers/${id}`),
  products: (params) => api.get('/api/admin/products', params),
  createProduct: (data) => api.post('/api/admin/products', data),
  updateProduct: (id, data) => api.put(`/api/admin/products/${id}`, data),
  deleteProduct: (id) => api.delete(`/api/admin/products/${id}`),
  warehouses: (params) => api.get('/api/admin/warehouses', params),
  createWarehouse: (data) => api.post('/api/admin/warehouses', data),
  updateWarehouse: (id, data) => api.put(`/api/admin/warehouses/${id}`, data),
  deleteWarehouse: (id) => api.delete(`/api/admin/warehouses/${id}`),
  bankAccounts: (params) => api.get('/api/admin/bank-accounts', params),
  createBankAccount: (data) => api.post('/api/admin/bank-accounts', data),
  updateBankAccount: (id, data) => api.put(`/api/admin/bank-accounts/${id}`, data),
  deleteBankAccount: (id) => api.delete(`/api/admin/bank-accounts/${id}`),
  bagTypes: (params) => api.get('/api/admin/bag-types', params),
  createBagType: (data) => api.post('/api/admin/bag-types', data),
  updateBagType: (id, data) => api.put(`/api/admin/bag-types/${id}`, data),
  deleteBagType: (id) => api.delete(`/api/admin/bag-types/${id}`),
  documentTemplates: (params) => api.get('/api/admin/document-templates', params),
  createDocumentTemplate: (data) => api.post('/api/admin/document-templates', data),
  updateDocumentTemplate: (id, data) => api.put(`/api/admin/document-templates/${id}`, data),
  deleteDocumentTemplate: (id) => api.delete(`/api/admin/document-templates/${id}`),
  productCategories: (params) => api.get('/api/admin/product-categories', params),
  createProductCategory: (data) => api.post('/api/admin/product-categories', data),
  updateProductCategory: (id, data) => api.put(`/api/admin/product-categories/${id}`, data),
  deleteProductCategory: (id) => api.delete(`/api/admin/product-categories/${id}`),
  // Roles & Permissions
  permissions: () => api.get('/api/admin/permissions'),
  rolesWithPermissions: () => api.get('/api/admin/roles-with-permissions'),
  updateRolePermissions: (roleId, data) => api.put(`/api/admin/roles/${roleId}/permissions`, data),
  settings: () => api.get('/api/admin/settings'),
  updateSettings: (data) => api.put('/api/admin/settings', data),
  auditLogs: (params) => api.get('/api/admin/audit-logs', params),
  // Master-data approvals (quick-add review queue)
  customersQuickAdd: (data) => api.post('/api/admin/customers/quick-add', data),
  suppliersQuickAdd: (data) => api.post('/api/admin/suppliers/quick-add', data),
  approvalsList:  (params) => api.get('/api/admin/approvals', params),
  approvalsCount: () => api.get('/api/admin/approvals/count'),
  approvalApprove: (type, id, body = {}) => api.post(`/api/admin/approvals/${type}/${id}/approve`, body),
  approvalReject:  (type, id, data) => api.post(`/api/admin/approvals/${type}/${id}/reject`, data),
  // Super-Admin Danger Zone (permanent hard-deletes + balance correction)
  dangerLotImpact:  (id) => api.get(`/api/admin/danger/lots/${id}/impact`),
  dangerDeleteLot:  (id, force) => api.delete(`/api/admin/danger/lots/${id}?confirm=DELETE${force ? '&force=true' : ''}`),
  dangerTxnImpact:  (type, id) => api.get(`/api/admin/danger/transactions/${type}/${id}/impact`),
  dangerDeleteTxn:  (type, id) => api.delete(`/api/admin/danger/transactions/${type}/${id}?confirm=DELETE`),
  dangerAdjustBalance: (id, data) => api.post(`/api/admin/danger/bank-accounts/${id}/balance`, data),
  dangerReset: (data) => api.post('/api/admin/danger/reset', data),
};
export const customersApi = {
  list: (params) => api.get('/api/customers', params),
  create: (data) => api.post('/api/customers', data),
  update: (id, data) => api.put(`/api/customers/${id}`, data),
  delete: (id) => api.delete(`/api/customers/${id}`),
};
export const usersApi = {
  list: (params) => api.get('/api/users', params),
  get: (id) => api.get(`/api/users/${id}`),
  create: (data) => api.post('/api/users', data),
  update: (id, data) => api.put(`/api/users/${id}`, data),
  changeRole: (id, data) => api.put(`/api/users/${id}/role`, data),
  deactivate: (id) => api.put(`/api/users/${id}/deactivate`),
  activate: (id) => api.put(`/api/users/${id}/activate`),
};
export const auditApi = {
  list: (params) => api.get('/api/audit-logs', params),
  byEntity: (type, id) => api.get(`/api/audit-logs/entity/${type}/${id}`),
  byUser: (userId, params) => api.get(`/api/audit-logs/user/${userId}`, params),
};
export const authApi = {
  login: (data) => api.post('/api/auth/login', data),
  me: () => api.get('/api/auth/me'),
  changePassword: (data) => api.post('/api/auth/change-password', data),
  forgotPassword: (data) => api.post('/api/auth/forgot-password', data),
  resetPassword: (data) => api.post('/api/auth/reset-password', data),
};
