import api from '../../../api/client';
export const financeApi = {
  overview: () => api.get('/api/finance/overview'),
  upcoming: () => api.get('/api/finance/upcoming'),
  clearCheque: (id, data) => api.post(`/api/finance/payments/${id}/clear`, data || {}),
  receivables: (params) => api.get('/api/finance/receivables', params),
  receivableReceipts: (id, source) => api.get(`/api/finance/receivables/${id}/receipts`, { source }),
  payablePayments: (id) => api.get(`/api/finance/payables/${id}/payments`),
  purchasePaymentTrail: (source, sourceId) => api.get(`/api/finance/purchases/${source}/${sourceId}/payments`),
  payables: (params) => api.get('/api/finance/payables', params),
  recordPayment: (data) => api.post('/api/finance/payments', data),
  reversePayment: (id, reason) => api.post(`/api/finance/payments/${id}/reverse`, { reason }),
  payments: (params) => api.get('/api/finance/payments', params),
  purchases: (params) => api.get('/api/finance/purchases', params),
  payPurchase: (data) => api.post('/api/finance/purchases/pay', data),
  bankAccounts: () => api.get('/api/finance/bank-accounts'),
  // Suspense Account (#8)
  suspenseList: (params) => api.get('/api/finance/suspense', params),
  suspenseSummary: () => api.get('/api/finance/suspense/summary'),
  suspenseGet: (id) => api.get(`/api/finance/suspense/${id}`),
  suspenseCreate: (data) => api.post('/api/finance/suspense', data),
  suspenseResolve: (id, data) => api.post(`/api/finance/suspense/${id}/resolve`, data),
  suspenseReverse: (id, data) => api.post(`/api/finance/suspense/${id}/reverse`, data || {}),
  suspenseReview: (id) => api.post(`/api/finance/suspense/${id}/review`, {}),
  chartOfAccounts: () => api.get('/api/accounting/accounts'),
  bankTransactions: (params) => api.get('/api/finance/bank-transactions', params),
  journalEntries: (params) => api.get('/api/finance/journal-entries', params),
  alerts: (params) => api.get('/api/finance/alerts', params),
  overviewSummary: (params) => api.get('/api/finance/overview-summary', params),
  profitabilitySummary: (params) => api.get('/api/finance/profitability-summary', params),
  internalTransfers: (params) => api.get('/api/finance/internal-transfers', params),
  internalTransfer: (id) => api.get(`/api/finance/internal-transfers/${id}`),
  createTransfer: (data) => api.post('/api/finance/internal-transfers', data),
  confirmTransferExport: (id) => api.put(`/api/finance/internal-transfers/${id}/confirm-export`),
  fundTransfers: (params) => api.get('/api/finance/fund-transfers', params),
  createFundTransfer: (data) => api.post('/api/finance/fund-transfers', data),
  acceptFundTransfer: (id, body = {}) => api.post(`/api/finance/fund-transfers/${id}/accept`, body),
  deleteFundTransfer: (id) => api.delete(`/api/finance/fund-transfers/${id}`),
  costAllocations: (params) => api.get('/api/finance/cost-allocations', params),
  createCostAllocation: (data) => api.post('/api/finance/cost-allocations', data),
  addAllocationLine: (id, data) => api.post(`/api/finance/cost-allocations/${id}/lines`, data),
  removeAllocationLine: (allocationId, lineId) => api.delete(`/api/finance/cost-allocations/${allocationId}/lines/${lineId}`),
  fxRates: (params) => api.get('/api/finance/fx-rates', params),
  addFxRate: (data) => api.post('/api/finance/fx-rates', data),
  refreshFxValues: () => api.post('/api/finance/fx-rates/refresh'),
  commodityRates: (params) => api.get('/api/finance/commodity-rates', params),
  addCommodityRate: (data) => api.post('/api/finance/commodity-rates', data),
};
export const advancesApi = {
  list: (params) => api.get('/api/advances', params),
  create: (data) => api.post('/api/advances', data),
  allocate: (id, data) => api.put(`/api/advances/${id}/allocate`, data),
};
