// Shared CSV + standardized-print helpers for the Phase 2 ledger reports.
// No new dependencies — CSV reuses the app-wide downloadCSV util; print opens
// a self-contained window with a standard template (company header ·
// filters-applied · generated-by/on · signature line) so every ledger prints
// the same way regardless of which drawer it lives in.
import { downloadCSV } from '../../../utils/csvExport';

// columns: [{ label, key?, accessor?(row), align? }]  rows: object[]
export function exportLedgerCSV({ filename = 'ledger.csv', columns, rows }) {
  downloadCSV(rows || [], columns || [], filename);
}

function esc(s) {
  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function cellValue(col, row) {
  const v = typeof col.accessor === 'function' ? col.accessor(row) : row[col.key];
  return v == null ? '' : v;
}

// Opens a print window with the standard ledger template and triggers print.
export function printLedger({ companyName = 'AGRI COMMODITIES', title, subtitle, meta = [], columns = [], rows = [], footerNote, generatedBy }) {
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const metaLine = [...meta, generatedBy ? `Generated by ${generatedBy}` : null, `On ${now}`].filter(Boolean).map(esc).join(' &nbsp;·&nbsp; ');

  const thead = columns.map(c => `<th style="text-align:${c.align || 'left'}">${esc(c.label)}</th>`).join('');
  const tbody = (rows || []).map(r => `<tr>${columns.map(c => `<td style="text-align:${c.align || 'left'}">${esc(cellValue(c, r))}</td>`).join('')}</tr>`).join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title || 'Ledger')}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #111827; margin: 28px; font-size: 12px; }
    .hdr { border-bottom: 2px solid #111827; padding-bottom: 10px; margin-bottom: 6px; }
    .company { font-size: 20px; font-weight: 800; letter-spacing: .5px; }
    .title { font-size: 15px; font-weight: 700; margin-top: 2px; }
    .subtitle { color: #6b7280; font-size: 12px; margin-top: 1px; }
    .meta { color: #6b7280; font-size: 10.5px; margin: 8px 0 14px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f3f4f6; font-size: 10px; text-transform: uppercase; letter-spacing: .4px; color: #374151; padding: 6px 8px; border-bottom: 1px solid #d1d5db; }
    td { padding: 5px 8px; border-bottom: 1px solid #f0f0f0; }
    tbody tr:nth-child(even) td { background: #fafafa; }
    .note { color: #6b7280; font-size: 10px; margin-top: 10px; }
    .sign { display: flex; justify-content: space-between; margin-top: 48px; gap: 24px; }
    .sign div { flex: 1; border-top: 1px solid #9ca3af; padding-top: 4px; text-align: center; color: #6b7280; font-size: 10.5px; }
    @media print { body { margin: 12mm; } }
  </style></head><body>
    <div class="hdr">
      <div class="company">${esc(companyName)}</div>
      <div class="title">${esc(title || 'Ledger Report')}</div>
      ${subtitle ? `<div class="subtitle">${esc(subtitle)}</div>` : ''}
    </div>
    <div class="meta">${metaLine}</div>
    <table><thead><tr>${thead}</tr></thead><tbody>${tbody || `<tr><td colspan="${columns.length}" style="color:#9ca3af">No rows.</td></tr>`}</tbody></table>
    ${footerNote ? `<div class="note">${esc(footerNote)}</div>` : ''}
    <div class="sign"><div>Prepared by</div><div>Checked by</div><div>Approved by</div></div>
  </body></html>`;

  const w = window.open('', '_blank', 'width=980,height=720');
  if (!w) return; // popup blocked
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  // Give the new document a tick to lay out before printing.
  setTimeout(() => { try { w.print(); } catch (e) { /* user can print manually */ } }, 350);
}
