// Shared CSV + standardized-print helpers for the Phase 2 ledger reports.
// No new dependencies — CSV reuses the app-wide downloadCSV util; print opens
// a self-contained window with a standard template (company header ·
// filters-applied · generated-by/on · signature line) so every ledger prints
// the same way regardless of which drawer it lives in.
import { downloadCSV } from '../../../utils/csvExport';

// columns: [{ label, key?, accessor?(row), align? }]  rows: object[]
export function exportLedgerCSV({ filename = 'ledger.csv', columns, rows }) {
  downloadCSV(rows || [], columns || [], filename);
}

function esc(s) {
  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function cellValue(col, row) {
  const v = typeof col.accessor === 'function' ? col.accessor(row) : row[col.key];
  return v == null ? '' : v;
}

// Opens a print window with the standard ledger template and triggers print.
export function printLedger({ companyName = 'AGRI COMMODITIES', title, subtitle, meta = [], columns = [], rows = [], footerNote, generatedBy }) {
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const metaLine = [...meta, generatedBy ? `Generated by ${generatedBy}` : null, `On ${now}`].filter(Boolean).map(esc).join(' &nbsp;·&nbsp; ');

  const thead = columns.map(c => `<th style="text-align:${c.align || 'left'}">${esc(c.label)}</th>`).join('');
  const tbody = (rows || []).map(r => `<tr>${columns.map(c => `<td style="text-align:${c.align || 'left'}">${esc(cellValue(c, r))}</td>`).join('')}</tr>`).join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title || 'Ledger')}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #111827; margin: 28px; font-size: 12px; }
    .hdr { border-bottom: 2px solid #111827; padding-bottom: 10px; margin-bottom: 6px; }
    .company { font-size: 20px; font-weight: 800; letter-spacing: .5px; }
    .title { font-size: 15px; font-weight: 700; margin-top: 2px; }
    .subtitle { color: #6b7280; font-size: 12px; margin-top: 1px; }
    .meta { color: #6b7280; font-size: 10.5px; margin: 8px 0 14px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f3f4f6; font-size: 10px; text-transform: uppercase; letter-spacing: .4px; color: #374151; padding: 6px 8px; border-bottom: 1px solid #d1d5db; }
    td { padding: 5px 8px; border-bottom: 1px solid #f0f0f0; }
    tbody tr:nth-child(even) td { background: #fafafa; }
    .note { color: #6b7280; font-size: 10px; margin-top: 10px; }
    .sign { display: flex; justify-content: space-between; margin-top: 48px; gap: 24px; }
    .sign div { flex: 1; border-top: 1px solid #9ca3af; padding-top: 4px; text-align: center; color: #6b7280; font-size: 10.5px; }
    @media print { body { margin: 12mm; } }
  </style></head><body>
    <div class="hdr">
      <div class="company">${esc(companyName)}</div>
      <div class="title">${esc(title || 'Ledger Report')}</div>
      ${subtitle ? `<div class="subtitle">${esc(subtitle)}</div>` : ''}
    </div>
    <div class="meta">${metaLine}</div>
    <table><thead><tr>${thead}</tr></thead><tbody>${tbody || `<tr><td colspan="${columns.length}" style="color:#9ca3af">No rows.</td></tr>`}</tbody></table>
    ${footerNote ? `<div class="note">${esc(footerNote)}</div>` : ''}
    <div class="sign"><div>Prepared by</div><div>Checked by</div><div>Approved by</div></div>
  </body></html>`;

  const w = window.open('', '_blank', 'width=980,height=720');
  if (!w) return; // popup blocked
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  // Give the new document a tick to lay out before printing.
  setTimeout(() => { try { w.print(); } catch (e) { /* user can print manually */ } }, 350);
}

// Full multi-section Lot 360 print (purchase → milling → output → sales →
// activity), A4. data = the /reporting/lot-ledger/:id payload.
export function printLotLedger(data, { companyName = 'AGRI COMMODITIES', generatedBy } = {}) {
  const e = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const pkr = (v) => `Rs ${Math.round(parseFloat(v) || 0).toLocaleString()}`;
  const kg = (v) => `${Math.round(parseFloat(v) || 0).toLocaleString()} kg`;
  const dd = (v) => v ? new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
  const { lot = {}, quantitySummary: qs = {}, financialSummary: fs = {}, millingHistory = [], outputs = [], directSales = [], processedSales = [], events = [] } = data;
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const sales = [...directSales, ...processedSales];
  const kv = (rows) => `<table class="kv">${rows.filter(Boolean).map(([k, v]) => `<tr><td class="k">${e(k)}</td><td class="v">${v}</td></tr>`).join('')}</table>`;
  const tbl = (head, rows) => `<table><thead><tr>${head.map(h => `<th style="text-align:${h.r ? 'right' : 'left'}">${e(h.t || h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((c, i) => `<td style="text-align:${head[i] && head[i].r ? 'right' : 'left'}">${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${head.length}" style="color:#9ca3af">None</td></tr>`}</tbody></table>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Lot ${e(lot.lotNo)}</title><style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#111827;margin:0;font-size:11px}
    .page{padding:12mm} .hdr{border-bottom:2px solid #111827;padding-bottom:8px;display:flex;justify-content:space-between}
    .co{font-size:18px;font-weight:800} .title{font-size:15px;font-weight:800;text-align:right} .muted{color:#6b7280;font-size:10px}
    h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#374151;margin:16px 0 5px;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
    table{width:100%;border-collapse:collapse;margin-top:3px} th{background:#f3f4f6;font-size:9px;text-transform:uppercase;color:#374151;padding:5px 7px;border-bottom:1px solid #d1d5db}
    td{padding:4px 7px;border-bottom:1px solid #f0f0f0} tbody tr:nth-child(even) td{background:#fafafa}
    table.kv{width:auto} table.kv td{border:0;padding:2px 10px 2px 0} table.kv .k{color:#6b7280} table.kv .v{font-weight:600}
    .grid2{display:flex;gap:32px} .grid2>div{flex:1}
    @media print{.page{padding:10mm}@page{size:A4 portrait;margin:0}}
  </style></head><body><div class="page">
    <div class="hdr"><div><div class="co">${e(companyName)}</div><div class="muted">Complete Lot Ledger / Lot 360</div></div>
      <div><div class="title">LOT ${e(lot.lotNo)}</div><div class="muted">${e(lot.riceType || '')}</div><div class="muted">${generatedBy ? 'By ' + e(generatedBy) + ' · ' : ''}${e(now)}</div></div></div>
    <div class="grid2"><div>${kv([
      ['Supplier', e(lot.supplier || '—')], ['Purchase date', dd(lot.purchaseDate)], ['Rice type / variety', e(lot.riceType || '—')],
      ['Warehouse', e(lot.warehouse || '—')], ['Truck', e(lot.truck || '—')], ['Driver', e(lot.driver || '—')],
    ])}</div><div>${kv([
      ['Grade', e(lot.grade || '—')], lot.moisturePct != null ? ['Moisture', e(lot.moisturePct) + '%'] : null, ['Bags', lot.bags != null ? e(lot.bags) : '—'],
      ['Purchase rate/kg', lot.ratePerKg ? pkr(lot.ratePerKg) : '—'], ['Landed cost/kg', lot.costPerKg ? pkr(lot.costPerKg) : '—'], ['Total purchase value', pkr(lot.valuePkr)],
    ])}</div></div>

    <h4>Quantity Summary</h4>
    ${kv([
      ['Purchased', kg(qs.purchasedKg)], ['Sent for milling', kg(qs.sentForMillingKg)], ['Sold without processing', kg(qs.soldWithoutProcessingKg)],
      ['Finished produced', kg(qs.finishedProducedKg)], ['Sold after processing', kg(qs.soldAfterProcessingKg)], ['Reserved', kg(qs.reservedKg)],
      ['Adjusted / rejected', kg(qs.adjustedKg)], ['Processing loss', kg(qs.processingLossKg)], ['Remaining', kg(qs.remainingKg)],
    ])}

    <h4>Financial Summary</h4>
    ${kv([
      ['Purchase value', pkr(fs.purchaseValue)], ['Processing cost allocated', pkr(fs.processingCostAllocated)], ['Cost of sold (COGS)', pkr(fs.totalCostOfSold)],
      ['Revenue — direct sale', pkr(fs.directRevenue)], ['Revenue — processed sale', pkr(fs.processedRevenue)], ['Total revenue', pkr(fs.totalRevenue)],
      ['Payment received', pkr(fs.paymentReceived)], ['Outstanding', pkr(fs.outstanding)],
      ['Realized profit', `${pkr(fs.realizedProfit)} (${(parseFloat(fs.realizedProfitPct) || 0).toFixed(1)}%)`],
      ['Remaining stock value', pkr(fs.remainingStockValue)], ['Expected profit on remaining', pkr(fs.expectedProfitRemaining)],
    ])}
    <div class="muted" style="margin-top:4px">${e(fs.costBasis || '')}</div>

    <h4>Milling / Processing History</h4>
    ${tbl([{ t: 'Date' }, { t: 'Batch' }, { t: 'Input', r: 1 }, { t: 'Output', r: 1 }, { t: 'Loss', r: 1 }], millingHistory.map(m => [dd(m.date), e(m.batchNo || '—'), kg(m.inputKg), kg(m.outputKg), kg(m.lossKg)]))}

    <h4>Output Produced &amp; By-product Pricing</h4>
    ${tbl([{ t: 'Batch' }, { t: 'Product / Grade' }, { t: 'Type' }, { t: 'Rice type' }, { t: 'Qty', r: 1 }, { t: 'Cost/kg', r: 1 }, { t: 'Sale price/kg', r: 1 }, { t: 'Recovery', r: 1 }, { t: 'Warehouse' }], outputs.map(o => [e(o.batchNo || '—'), e(o.productGrade), o.type === 'byproduct' ? 'by-product' : 'finished', e(o.riceType), kg(o.qtyKg), o.costPerKg ? pkr(o.costPerKg) : '—', o.salePricePerKg ? pkr(o.salePricePerKg) : '—', o.recoveryValue ? pkr(o.recoveryValue) : '—', e(o.warehouse || '—')]))}

    <h4>Sales From This Lot</h4>
    ${tbl([{ t: 'Date' }, { t: 'Invoice' }, { t: 'Customer' }, { t: 'Type' }, { t: 'Product' }, { t: 'Qty', r: 1 }, { t: 'Amount', r: 1 }], sales.map(s => [dd(s.date), e(s.invoice), e(s.customer), e(s.kind), e(s.product || '—'), kg(s.qtyKg), pkr(s.amount)]))}

    <h4>Lot Activity Ledger</h4>
    ${tbl([{ t: 'Date' }, { t: 'Activity' }, { t: 'Ref' }, { t: 'In', r: 1 }, { t: 'Out', r: 1 }, { t: 'Balance', r: 1 }], events.map(ev => [dd(ev.date), e(ev.label), e(ev.reference || ev.txnNo || '—'), ev.inKg ? kg(ev.inKg) : '', ev.outKg ? kg(ev.outKg) : '', kg(ev.balanceKg)]))}
  </div><script>window.addEventListener('load',function(){setTimeout(function(){window.focus();window.print();},350)});<\/script></body></html>`;
  const w = window.open('', '_blank', 'width=980,height=1200');
  if (!w) return false;
  w.document.open(); w.document.write(html); w.document.close(); w.focus();
  return true;
}

// Full Supplier Inventory Ledger / Supplier 360 print — summary + per-lot
// purchased/milled/sold/remaining/value/profit, A4. data = the
// /reporting/supplier-ledger/:id payload.
export function printSupplierLedger(data, { companyName = 'AGRI COMMODITIES', generatedBy } = {}) {
  const e = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const pkr = (v) => `Rs ${Math.round(parseFloat(v) || 0).toLocaleString()}`;
  const kg = (v) => `${Math.round(parseFloat(v) || 0).toLocaleString()} kg`;
  const dd = (v) => v ? new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
  const { supplier: sup = {}, summary: sm = {}, lots = [] } = data;
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const kv = (rows) => `<table class="kv">${rows.filter(Boolean).map(([k, v]) => `<tr><td class="k">${e(k)}</td><td class="v">${v}</td></tr>`).join('')}</table>`;
  const tbl = (head, rows) => `<table><thead><tr>${head.map(h => `<th style="text-align:${h.r ? 'right' : 'left'}">${e(h.t || h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((c, i) => `<td style="text-align:${head[i] && head[i].r ? 'right' : 'left'}">${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${head.length}" style="color:#9ca3af">None</td></tr>`}</tbody></table>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Supplier ${e(sup.name)}</title><style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#111827;margin:0;font-size:11px}
    .page{padding:12mm} .hdr{border-bottom:2px solid #111827;padding-bottom:8px;display:flex;justify-content:space-between}
    .co{font-size:18px;font-weight:800} .title{font-size:15px;font-weight:800;text-align:right} .muted{color:#6b7280;font-size:10px}
    h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#374151;margin:16px 0 5px;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
    table{width:100%;border-collapse:collapse;margin-top:3px} th{background:#f3f4f6;font-size:9px;text-transform:uppercase;color:#374151;padding:5px 7px;border-bottom:1px solid #d1d5db}
    td{padding:4px 7px;border-bottom:1px solid #f0f0f0} tbody tr:nth-child(even) td{background:#fafafa}
    table.kv{width:auto} table.kv td{border:0;padding:2px 10px 2px 0} table.kv .k{color:#6b7280} table.kv .v{font-weight:600}
    .grid2{display:flex;gap:32px} .grid2>div{flex:1}
    @media print{.page{padding:10mm}@page{size:A4 landscape;margin:0}}
  </style></head><body><div class="page">
    <div class="hdr"><div><div class="co">${e(companyName)}</div><div class="muted">Supplier Inventory Ledger / Supplier 360</div></div>
      <div><div class="title">${e(sup.name)}</div><div class="muted">${e(sup.country || '')}</div><div class="muted">${generatedBy ? 'By ' + e(generatedBy) + ' · ' : ''}${e(now)}</div></div></div>
    <div class="grid2"><div>${kv([
      ['Contact', e(sup.contactPerson || '—')], ['Phone', e(sup.phone || '—')], ['Lots purchased', e(sm.lotCount)],
      ['Total purchased', kg(sm.purchasedKg)], ['Total milled', kg(sm.milledKg)], ['Total sold', kg(sm.soldKg)],
      ['Remaining stock', kg(sm.remainingKg)], ['Processing loss', kg(sm.lossKg)],
    ])}</div><div>${kv([
      ['Stock value', pkr(sm.stockValue)], ['Revenue generated', pkr(sm.revenue)],
      ['Realized profit', `${pkr(sm.realizedProfit)} (${(parseFloat(sm.realizedProfitPct) || 0).toFixed(1)}%)`],
      ['Expected profit on remaining', pkr(sm.expectedProfitRemaining)],
      ['Payable outstanding', pkr(sm.payableOutstanding)], ['Payments made', pkr(sm.payablePaid)],
      ['Avg yield', sm.avgYieldPct != null ? `${(parseFloat(sm.avgYieldPct) || 0).toFixed(1)}%` : '—'],
      ['Avg moisture', sm.avgMoisture != null ? `${(parseFloat(sm.avgMoisture) || 0).toFixed(1)}%` : '—'],
    ])}</div></div>

    <h4>Lots from this supplier</h4>
    ${tbl([{ t: 'Lot' }, { t: 'Rice type' }, { t: 'Purchased', r: 1 }, { t: 'Milled', r: 1 }, { t: 'Sold', r: 1 }, { t: 'Remaining', r: 1 }, { t: 'Cost/kg', r: 1 }, { t: 'Stock value', r: 1 }, { t: 'Revenue', r: 1 }, { t: 'Realized profit', r: 1 }],
      lots.map(l => [e(l.lotNo), e(l.riceType || '—'), kg(l.purchasedKg), kg(l.milledKg), kg(l.soldKg), kg(l.remainingKg), l.costPerKg ? pkr(l.costPerKg) : '—', pkr(l.stockValue), pkr(l.revenue), pkr(l.realizedProfit)]))}
    <div class="muted" style="margin-top:6px">${e(sm.costBasis || '')}</div>
  </div><script>window.addEventListener('load',function(){setTimeout(function(){window.focus();window.print();},350)});<\/script></body></html>`;
  const w = window.open('', '_blank', 'width=1100,height=900');
  if (!w) return false;
  w.document.open(); w.document.write(html); w.document.close(); w.focus();
  return true;
}

// Full Rice Type Ledger print — summary + supplier/warehouse breakdown +
// per-lot rows, A4. data = the /reporting/rice-type-ledger/:id payload.
export function printRiceTypeLedger(data, { companyName = 'AGRI COMMODITIES', generatedBy } = {}) {
  const e = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const pkr = (v) => `Rs ${Math.round(parseFloat(v) || 0).toLocaleString()}`;
  const kg = (v) => `${Math.round(parseFloat(v) || 0).toLocaleString()} kg`;
  const dd = (v) => v ? new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
  const { riceType: rt = {}, summary: sm = {}, bySupplier = [], byWarehouse = [], lots = [] } = data;
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const kv = (rows) => `<table class="kv">${rows.filter(Boolean).map(([k, v]) => `<tr><td class="k">${e(k)}</td><td class="v">${v}</td></tr>`).join('')}</table>`;
  const tbl = (head, rows) => `<table><thead><tr>${head.map(h => `<th style="text-align:${h.r ? 'right' : 'left'}">${e(h.t || h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((c, i) => `<td style="text-align:${head[i] && head[i].r ? 'right' : 'left'}">${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${head.length}" style="color:#9ca3af">None</td></tr>`}</tbody></table>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Rice type ${e(rt.name)}</title><style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#111827;margin:0;font-size:11px}
    .page{padding:12mm} .hdr{border-bottom:2px solid #111827;padding-bottom:8px;display:flex;justify-content:space-between}
    .co{font-size:18px;font-weight:800} .title{font-size:15px;font-weight:800;text-align:right} .muted{color:#6b7280;font-size:10px}
    h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#374151;margin:16px 0 5px;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
    table{width:100%;border-collapse:collapse;margin-top:3px} th{background:#f3f4f6;font-size:9px;text-transform:uppercase;color:#374151;padding:5px 7px;border-bottom:1px solid #d1d5db}
    td{padding:4px 7px;border-bottom:1px solid #f0f0f0} tbody tr:nth-child(even) td{background:#fafafa}
    table.kv{width:auto} table.kv td{border:0;padding:2px 10px 2px 0} table.kv .k{color:#6b7280} table.kv .v{font-weight:600}
    .grid2{display:flex;gap:32px} .grid2>div{flex:1}
    @media print{.page{padding:10mm}@page{size:A4 landscape;margin:0}}
  </style></head><body><div class="page">
    <div class="hdr"><div><div class="co">${e(companyName)}</div><div class="muted">Rice Type Ledger</div></div>
      <div><div class="title">${e(rt.name)}</div><div class="muted">${e(rt.grade || '')}</div><div class="muted">${generatedBy ? 'By ' + e(generatedBy) + ' · ' : ''}${e(now)}</div></div></div>
    <div class="grid2"><div>${kv([
      ['Lots', e(sm.lotCount)], ['Purchased', kg(sm.purchasedKg)], ['Milled / processed', kg(sm.milledKg)],
      ['Produced (finished)', kg(sm.producedKg)], ['Sold', kg(sm.soldKg)], ['Exported', kg(sm.exportedKg)],
      ['Reserved', kg(sm.reservedKg)], ['Remaining stock', kg(sm.remainingKg)],
    ])}</div><div>${kv([
      ['Stock value', pkr(sm.stockValue)], ['Average cost/kg', pkr(sm.avgCost)], ['Average sale rate/kg', pkr(sm.avgSaleRate)],
      ['Revenue', pkr(sm.revenue)], ['Cost of sold (COGS)', pkr(sm.cogs)],
      ['Realized profit', `${pkr(sm.realizedProfit)} (${(parseFloat(sm.realizedProfitPct) || 0).toFixed(1)}%)`],
      ['Expected profit on remaining', pkr(sm.expectedProfitRemaining)],
    ])}</div></div>

    <h4>By supplier (raw side)</h4>
    ${tbl([{ t: 'Supplier' }, { t: 'Purchased', r: 1 }, { t: 'Remaining', r: 1 }, { t: 'Value', r: 1 }], bySupplier.map(s => [e(s.supplier || '—'), kg(s.purchasedKg), kg(s.remainingKg), pkr(s.value)]))}

    <h4>By warehouse</h4>
    ${tbl([{ t: 'Warehouse' }, { t: 'Remaining', r: 1 }, { t: 'Value', r: 1 }], byWarehouse.map(w => [e(w.warehouse || '—'), kg(w.remainingKg), pkr(w.value)]))}

    <h4>Lots of this rice type</h4>
    ${tbl([{ t: 'Lot' }, { t: 'Type' }, { t: 'Supplier' }, { t: 'Warehouse' }, { t: 'Purchased', r: 1 }, { t: 'Produced', r: 1 }, { t: 'Remaining', r: 1 }, { t: 'Cost/kg', r: 1 }, { t: 'Value', r: 1 }],
      lots.map(l => [e(l.lotNo), e(l.type), e(l.supplier || '—'), e(l.warehouse || '—'), kg(l.purchasedKg), kg(l.producedKg), kg(l.remainingKg), l.costPerKg ? pkr(l.costPerKg) : '—', pkr(l.value)]))}
    <div class="muted" style="margin-top:6px">${e(sm.costBasis || '')}</div>
  </div><script>window.addEventListener('load',function(){setTimeout(function(){window.focus();window.print();},350)});<\/script></body></html>`;
  const w = window.open('', '_blank', 'width=1100,height=900');
  if (!w) return false;
  w.document.open(); w.document.write(html); w.document.close(); w.focus();
  return true;
}

// Full Warehouse Ledger print — summary + by-rice-type + per-lot roll-forward,
// A4. data = the /reporting/warehouse-ledger/:id payload.
export function printWarehouseLedger(data, { companyName = 'AGRI COMMODITIES', generatedBy } = {}) {
  const e = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const pkr = (v) => `Rs ${Math.round(parseFloat(v) || 0).toLocaleString()}`;
  const kg = (v) => `${Math.round(parseFloat(v) || 0).toLocaleString()} kg`;
  const { warehouse: wh = {}, summary: sm = {}, byRiceType = [], lots = [] } = data;
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const kv = (rows) => `<table class="kv">${rows.filter(Boolean).map(([k, v]) => `<tr><td class="k">${e(k)}</td><td class="v">${v}</td></tr>`).join('')}</table>`;
  const tbl = (head, rows) => `<table><thead><tr>${head.map(h => `<th style="text-align:${h.r ? 'right' : 'left'}">${e(h.t || h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((c, i) => `<td style="text-align:${head[i] && head[i].r ? 'right' : 'left'}">${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${head.length}" style="color:#9ca3af">None</td></tr>`}</tbody></table>`;
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Warehouse ${e(wh.name)}</title><style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#111827;margin:0;font-size:11px}
    .page{padding:12mm} .hdr{border-bottom:2px solid #111827;padding-bottom:8px;display:flex;justify-content:space-between}
    .co{font-size:18px;font-weight:800} .title{font-size:15px;font-weight:800;text-align:right} .muted{color:#6b7280;font-size:10px}
    h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#374151;margin:16px 0 5px;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
    table{width:100%;border-collapse:collapse;margin-top:3px} th{background:#f3f4f6;font-size:9px;text-transform:uppercase;color:#374151;padding:5px 7px;border-bottom:1px solid #d1d5db}
    td{padding:4px 7px;border-bottom:1px solid #f0f0f0} tbody tr:nth-child(even) td{background:#fafafa}
    table.kv{width:auto} table.kv td{border:0;padding:2px 10px 2px 0} table.kv .k{color:#6b7280} table.kv .v{font-weight:600}
    .grid2{display:flex;gap:32px} .grid2>div{flex:1}
    @media print{.page{padding:10mm}@page{size:A4 landscape;margin:0}}
  </style></head><body><div class="page">
    <div class="hdr"><div><div class="co">${e(companyName)}</div><div class="muted">Warehouse Ledger</div></div>
      <div><div class="title">${e(wh.name)}</div><div class="muted">${e(wh.entity || '')}${wh.type ? ' · ' + e(wh.type) : ''}</div><div class="muted">${generatedBy ? 'By ' + e(generatedBy) + ' · ' : ''}${e(now)}</div></div></div>
    <div class="grid2"><div>${kv([
      ['Lots on hand', e(sm.lotCount)], ['Total intake (in)', kg(sm.totalInKg)], ['Total out', kg(sm.totalOutKg)],
    ])}</div><div>${kv([
      ['On-hand (closing)', kg(sm.onHandKg)], ['Reserved', kg(sm.reservedKg)], ['Available', kg(sm.availableKg)], ['Stock value', pkr(sm.stockValue)],
    ])}</div></div>

    <h4>By rice type</h4>
    ${tbl([{ t: 'Rice type' }, { t: 'Lots', r: 1 }, { t: 'On hand', r: 1 }, { t: 'Reserved', r: 1 }, { t: 'Value', r: 1 }], byRiceType.map(r => [e(r.riceType || '—'), r.lots, kg(r.onHandKg), kg(r.reservedKg), pkr(r.value)]))}

    <h4>Lots in this warehouse</h4>
    ${tbl([{ t: 'Lot' }, { t: 'Rice type' }, { t: 'Type' }, { t: 'In', r: 1 }, { t: 'Out', r: 1 }, { t: 'Reserved', r: 1 }, { t: 'Available', r: 1 }, { t: 'Closing', r: 1 }, { t: 'Cost/kg', r: 1 }, { t: 'Value', r: 1 }],
      lots.map(l => [e(l.lotNo), e(l.riceType || '—'), e(l.type), kg(l.inKg), kg(l.outKg), kg(l.reservedKg), kg(l.availableKg), kg(l.closingKg), l.costPerKg ? pkr(l.costPerKg) : '—', pkr(l.value)]))}
    <div class="muted" style="margin-top:6px">${e(sm.costBasis || '')}</div>
  </div><script>window.addEventListener('load',function(){setTimeout(function(){window.focus();window.print();},350)});<\/script></body></html>`;
  const w = window.open('', '_blank', 'width=1100,height=900');
  if (!w) return false;
  w.document.open(); w.document.write(html); w.document.close(); w.focus();
  return true;
}

// Full multi-section Batch 360 print (inputs → processing → outputs → sales →
// financials), A4. data = the /reporting/batch-ledger/:id payload.
export function printBatchLedger(data, { companyName = 'AGRI COMMODITIES', generatedBy } = {}) {
  const e = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const pkr = (v) => `Rs ${Math.round(parseFloat(v) || 0).toLocaleString()}`;
  const kg = (v) => `${Math.round(parseFloat(v) || 0).toLocaleString()} kg`;
  const mt = (v) => `${(parseFloat(v) || 0).toFixed(2)} MT`;
  const dd = (v) => v ? new Date(v).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
  const { batch: b = {}, inputs = [], outputs = [], sales = [], costs = [], manualCosts: mc = {}, yieldSummary: ys = {}, financialSummary: fs = {} } = data;
  const now = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const kv = (rows) => `<table class="kv">${rows.filter(Boolean).map(([k, v]) => `<tr><td class="k">${e(k)}</td><td class="v">${v}</td></tr>`).join('')}</table>`;
  const tbl = (head, rows) => `<table><thead><tr>${head.map(h => `<th style="text-align:${h.r ? 'right' : 'left'}">${e(h.t || h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((c, i) => `<td style="text-align:${head[i] && head[i].r ? 'right' : 'left'}">${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${head.length}" style="color:#9ca3af">None</td></tr>`}</tbody></table>`;
  const costRows = [
    mc.milling ? ['Milling fee (manual)', pkr(mc.milling)] : null,
    mc.other ? ['Other expenses (manual)', pkr(mc.other)] : null,
    ...costs.filter(c => c.category !== 'raw_rice').map(c => [`${(c.category || 'cost')}${c.notes ? ' · ' + c.notes : ''}`, pkr(c.amount)]),
  ].filter(Boolean);
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Batch ${e(b.batchNo)}</title><style>
    *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#111827;margin:0;font-size:11px}
    .page{padding:12mm} .hdr{border-bottom:2px solid #111827;padding-bottom:8px;display:flex;justify-content:space-between}
    .co{font-size:18px;font-weight:800} .title{font-size:15px;font-weight:800;text-align:right} .muted{color:#6b7280;font-size:10px}
    h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:#374151;margin:16px 0 5px;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
    table{width:100%;border-collapse:collapse;margin-top:3px} th{background:#f3f4f6;font-size:9px;text-transform:uppercase;color:#374151;padding:5px 7px;border-bottom:1px solid #d1d5db}
    td{padding:4px 7px;border-bottom:1px solid #f0f0f0} tbody tr:nth-child(even) td{background:#fafafa}
    table.kv{width:auto} table.kv td{border:0;padding:2px 10px 2px 0} table.kv .k{color:#6b7280} table.kv .v{font-weight:600}
    .grid2{display:flex;gap:32px} .grid2>div{flex:1}
    @media print{.page{padding:10mm}@page{size:A4 portrait;margin:0}}
  </style></head><body><div class="page">
    <div class="hdr"><div><div class="co">${e(companyName)}</div><div class="muted">Complete Batch Ledger / Batch 360</div></div>
      <div><div class="title">BATCH ${e(b.batchNo)}</div><div class="muted">${e(b.product || '')}${b.isBlend ? ' · blend' : ''}</div><div class="muted">${generatedBy ? 'By ' + e(generatedBy) + ' · ' : ''}${e(now)}</div></div></div>
    <div class="grid2"><div>${kv([
      ['Status', e(b.status || '—')], ['Type', b.isBlend ? 'Blend' : 'Milling'], ['Product', e(b.product || '—')],
      ['Operator', e(b.operator || '—')], ['Machine line', e(b.machineLine || '—')], ['Shift', e(b.shift || '—')],
    ])}</div><div>${kv([
      ['Created', dd(b.createdAt)], ['Completed', dd(b.completedAt)], ['Processing hours', b.processingHours || '—'],
      ['Input', mt(ys.inputMt)], ['Finished', mt(ys.finishedMt)], ['Yield', `${(parseFloat(ys.yieldPct) || 0).toFixed(1)}%`],
    ])}</div></div>

    <h4>Yield Summary</h4>
    ${kv([['Input', mt(ys.inputMt)], ['Finished', mt(ys.finishedMt)], ['By-product', mt(ys.byproductMt)], ['Total output', mt(ys.totalOutputMt)], ['Processing loss', mt(ys.lossMt)], ['Yield %', `${(parseFloat(ys.yieldPct) || 0).toFixed(1)}%`]])}

    <h4>Financial Summary</h4>
    ${kv([
      ['Raw rice cost', pkr(fs.rawCost)], ['Processing cost', pkr(fs.processingCost)], ['Total input cost', pkr(fs.totalInputCost)],
      ['Output value (at cost)', pkr(fs.outputValue)], ['By-product recovery (valued)', pkr(fs.byproductRecovery)], ['Revenue (sold output)', pkr(fs.revenue)], ['Cost of sold (COGS)', pkr(fs.cogsOfSold)],
      ['Realized profit', `${pkr(fs.realizedProfit)} (${(parseFloat(fs.realizedProfitPct) || 0).toFixed(1)}%)`],
      ['Payment received', pkr(fs.paymentReceived)], ['Outstanding', pkr(fs.outstanding)],
      ['On-hand output value', pkr(fs.onHandValue)], ['Expected profit on remaining', pkr(fs.expectedProfitRemaining)],
    ])}
    <div class="muted" style="margin-top:4px">${e(fs.costBasis || '')}</div>

    <h4>Inputs — source rice lots</h4>
    ${tbl([{ t: 'Lot' }, { t: 'Rice' }, { t: 'Supplier' }, { t: 'Qty', r: 1 }, { t: 'Cost', r: 1 }], inputs.map(i => [e(i.lotNo || '—'), e(i.item || i.variety || '—'), e(i.supplier || '—'), mt(i.qtyMt), pkr(i.costTotalPkr)]))}

    <h4>Processing costs</h4>
    ${costRows.length ? kv(costRows) : '<div class="muted">No recorded processing costs.</div>'}

    <h4>Output produced &amp; by-product pricing</h4>
    ${tbl([{ t: 'Lot' }, { t: 'Product / Grade' }, { t: 'Type' }, { t: 'Produced', r: 1 }, { t: 'Sold', r: 1 }, { t: 'Remaining', r: 1 }, { t: 'Cost/kg', r: 1 }, { t: 'Sale price/kg', r: 1 }, { t: 'Recovery', r: 1 }], outputs.map(o => [e(o.lotNo), e(o.item), o.type === 'byproduct' ? 'by-product' : 'finished', kg(o.producedKg), kg(o.soldKg), kg(o.remainingKg), o.costPerKg ? pkr(o.costPerKg) : '—', o.salePricePerKg ? pkr(o.salePricePerKg) : '—', o.recoveryValue ? pkr(o.recoveryValue) : '—']))}

    <h4>Sales from this batch</h4>
    ${tbl([{ t: 'Date' }, { t: 'Invoice' }, { t: 'Customer' }, { t: 'Product' }, { t: 'Qty', r: 1 }, { t: 'Amount', r: 1 }], sales.map(s => [dd(s.date), e(s.invoice), e(s.customer), e(s.product || '—'), kg(s.qtyKg), pkr(s.amount)]))}
  </div><script>window.addEventListener('load',function(){setTimeout(function(){window.focus();window.print();},350)});<\/script></body></html>`;
  const w = window.open('', '_blank', 'width=980,height=1200');
  if (!w) return false;
  w.document.open(); w.document.write(html); w.document.close(); w.focus();
  return true;
}
