/**
 * Seed: Export Orders (10 orders from mockData)
 */

exports.seed = async function (knex) {
  // Clear in reverse-dependency order
  await knex.raw('TRUNCATE TABLE export_order_status_history, export_order_documents, export_order_costs, export_orders RESTART IDENTITY CASCADE');

  // Look up admin user ID dynamically
  const adminUser = await knex('users').where('email', 'admin@riceflow.com').first();
  const adminId = adminUser ? adminUser.id : null;

  // --- Order definitions from mockData ---
  const orders = [
    {
      order_no: 'EX-101',
      customer_id: 1,
      country: 'UAE',
      product_id: 14,
      product_name: 'IRRI-6 Long Grain Parboiled Rice',
      qty_mt: 50,
      price_per_mt: 520,
      currency: 'USD',
      contract_value: 26000,
      incoterm: 'CNF',
      advance_pct: 20,
      advance_expected: 5200,
      advance_received: 5200,
      advance_date: '2026-01-15',
      balance_expected: 20800,
      balance_received: 20800,
      balance_date: '2026-02-20',
      status: 'Shipped',
      current_step: 7,
      shipment_eta: '2026-02-10',
      source: 'Internal Mill',
      vessel_name: 'MV Atlantic Star',
      booking_no: 'BK-20260115',
      etd: '2026-02-25',
      atd: '2026-02-26',
      eta: '2026-03-15',
      ata: null,
      destination_port: 'Jebel Ali, Dubai',
      created_at: '2026-01-05',
      costs: { rice: 13000, bags: 1250, loading: 800, clearing: 650, freight: 3200, misc: 400 },
      documents: {
        phyto: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-18' },
        blDraft: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-20' },
        blFinal: { status: 'Approved', uploaded_by: 'Shipping Line', date: '2026-02-26' },
        invoice: { status: 'Approved', uploaded_by: 'Finance', date: '2026-02-22' },
        packingList: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-22' },
        coo: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-23' },
        fumigation: { status: 'Approved', uploaded_by: 'QC Team', date: '2026-02-24' },
      },
    },
    {
      order_no: 'EX-102',
      customer_id: 2,
      country: 'SAUDI ARABIA',
      product_id: 14,
      product_name: 'IRRI-6 Long Grain Parboiled Rice',
      qty_mt: 25,
      price_per_mt: 530,
      currency: 'USD',
      contract_value: 13250,
      incoterm: 'FOB',
      advance_pct: 20,
      advance_expected: 2650,
      advance_received: 2650,
      advance_date: '2026-02-05',
      balance_expected: 10600,
      balance_received: 0,
      balance_date: null,
      status: 'Awaiting Balance',
      current_step: 5,
      shipment_eta: '2026-03-20',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Jeddah, Saudi Arabia',
      created_at: '2026-01-28',
      costs: { rice: 6500, bags: 625, loading: 400, clearing: 350, freight: 0, misc: 200 },
      documents: {
        phyto: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-03-01' },
        blDraft: { status: 'Draft Uploaded', uploaded_by: 'Doc Officer', date: '2026-03-05' },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-103',
      customer_id: 3,
      country: 'NIGERIA',
      product_id: 8,
      product_name: 'C9 Long Grain Parboiled Rice',
      qty_mt: 100,
      price_per_mt: 450,
      currency: 'USD',
      contract_value: 45000,
      incoterm: 'CIF',
      advance_pct: 25,
      advance_expected: 11250,
      advance_received: 11250,
      advance_date: '2026-02-15',
      balance_expected: 33750,
      balance_received: 33750,
      balance_date: '2026-03-10',
      status: 'Arrived',
      current_step: 8,
      shipment_eta: '2026-03-05',
      source: 'Internal Mill',
      vessel_name: 'MV Sahel Breeze',
      booking_no: 'BK-20260202',
      etd: '2026-02-28',
      atd: '2026-03-01',
      eta: '2026-03-10',
      ata: '2026-03-12',
      destination_port: 'Lagos, Nigeria',
      created_at: '2026-01-10',
      costs: { rice: 24000, bags: 2500, loading: 1500, clearing: 1200, freight: 6500, misc: 800 },
      documents: {
        phyto: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-20' },
        blDraft: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-22' },
        blFinal: { status: 'Approved', uploaded_by: 'Shipping Line', date: '2026-03-01' },
        invoice: { status: 'Approved', uploaded_by: 'Finance', date: '2026-02-24' },
        packingList: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-24' },
        coo: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-02-25' },
        fumigation: { status: 'Approved', uploaded_by: 'QC Team', date: '2026-02-26' },
      },
    },
    {
      order_no: 'EX-104',
      customer_id: 4,
      country: 'GERMANY',
      product_id: 15,
      product_name: 'IRRI-6 Long Grain White Rice',
      qty_mt: 30,
      price_per_mt: 600,
      currency: 'USD',
      contract_value: 18000,
      incoterm: 'CIF',
      advance_pct: 20,
      advance_expected: 3600,
      advance_received: 0,
      advance_date: null,
      balance_expected: 14400,
      balance_received: 0,
      balance_date: null,
      status: 'Awaiting Advance',
      current_step: 2,
      shipment_eta: '2026-04-15',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Hamburg, Germany',
      created_at: '2026-02-20',
      costs: { rice: 0, bags: 0, loading: 0, clearing: 0, freight: 0, misc: 0 },
      documents: {
        phyto: { status: 'Pending', uploaded_by: null, date: null },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-105',
      customer_id: 5,
      country: 'SINGAPORE',
      product_id: 14,
      product_name: 'IRRI-6 Long Grain Parboiled Rice',
      qty_mt: 40,
      price_per_mt: 540,
      currency: 'USD',
      contract_value: 21600,
      incoterm: 'FOB',
      advance_pct: 15,
      advance_expected: 3240,
      advance_received: 3240,
      advance_date: '2026-03-01',
      balance_expected: 18360,
      balance_received: 0,
      balance_date: null,
      status: 'In Milling',
      current_step: 3,
      shipment_eta: '2026-04-25',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Singapore Port',
      created_at: '2026-02-15',
      costs: { rice: 10400, bags: 1000, loading: 0, clearing: 0, freight: 0, misc: 0 },
      documents: {
        phyto: { status: 'Pending', uploaded_by: null, date: null },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-106',
      customer_id: 6,
      country: 'SENEGAL',
      product_id: 25,
      product_name: 'PK-386 Long Grain Parboiled Rice',
      qty_mt: 75,
      price_per_mt: 410,
      currency: 'USD',
      contract_value: 30750,
      incoterm: 'CNF',
      advance_pct: 20,
      advance_expected: 6150,
      advance_received: 6150,
      advance_date: '2026-02-28',
      balance_expected: 24600,
      balance_received: 0,
      balance_date: null,
      status: 'Docs In Preparation',
      current_step: 4,
      shipment_eta: '2026-04-10',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Dakar, Senegal',
      created_at: '2026-02-10',
      costs: { rice: 16500, bags: 1875, loading: 1100, clearing: 900, freight: 4500, misc: 500 },
      documents: {
        phyto: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-03-08' },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Draft Uploaded', uploaded_by: 'Finance', date: '2026-03-10' },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-107',
      customer_id: 7,
      country: 'OMAN',
      product_id: 34,
      product_name: 'Super Kernel Basmati White Rice',
      qty_mt: 20,
      price_per_mt: 580,
      currency: 'USD',
      contract_value: 11600,
      incoterm: 'FOB',
      advance_pct: 25,
      advance_expected: 2900,
      advance_received: 2900,
      advance_date: '2026-03-05',
      balance_expected: 8700,
      balance_received: 0,
      balance_date: null,
      status: 'Procurement Pending',
      current_step: 3,
      shipment_eta: '2026-05-01',
      source: 'External Supplier',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Muscat, Oman',
      created_at: '2026-02-25',
      costs: { rice: 0, bags: 0, loading: 0, clearing: 0, freight: 0, misc: 0 },
      documents: {
        phyto: { status: 'Pending', uploaded_by: null, date: null },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-108',
      customer_id: 1,
      country: 'UAE',
      product_id: 8,
      product_name: 'C9 Long Grain Parboiled Rice',
      qty_mt: 60,
      price_per_mt: 460,
      currency: 'USD',
      contract_value: 27600,
      incoterm: 'CNF',
      advance_pct: 20,
      advance_expected: 5520,
      advance_received: 0,
      advance_date: null,
      balance_expected: 22080,
      balance_received: 0,
      balance_date: null,
      status: 'Draft',
      current_step: 1,
      shipment_eta: '2026-05-15',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Jebel Ali, Dubai',
      created_at: '2026-03-15',
      costs: { rice: 0, bags: 0, loading: 0, clearing: 0, freight: 0, misc: 0 },
      documents: {
        phyto: { status: 'Pending', uploaded_by: null, date: null },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
    {
      order_no: 'EX-109',
      customer_id: 3,
      country: 'NIGERIA',
      product_id: 14,
      product_name: 'IRRI-6 Long Grain Parboiled Rice',
      qty_mt: 80,
      price_per_mt: 510,
      currency: 'USD',
      contract_value: 40800,
      incoterm: 'CIF',
      advance_pct: 20,
      advance_expected: 8160,
      advance_received: 8160,
      advance_date: '2026-01-20',
      balance_expected: 32640,
      balance_received: 32640,
      balance_date: '2026-02-15',
      status: 'Closed',
      current_step: 9,
      shipment_eta: '2026-02-01',
      source: 'Internal Mill',
      vessel_name: 'MV Lagos Express',
      booking_no: 'BK-20260110',
      etd: '2026-02-01',
      atd: '2026-02-02',
      eta: '2026-02-12',
      ata: '2026-02-13',
      destination_port: 'Lagos, Nigeria',
      created_at: '2025-12-20',
      costs: { rice: 20800, bags: 2000, loading: 1200, clearing: 1000, freight: 5600, misc: 600 },
      documents: {
        phyto: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-01-25' },
        blDraft: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-01-27' },
        blFinal: { status: 'Approved', uploaded_by: 'Shipping Line', date: '2026-02-02' },
        invoice: { status: 'Approved', uploaded_by: 'Finance', date: '2026-01-28' },
        packingList: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-01-28' },
        coo: { status: 'Approved', uploaded_by: 'Doc Officer', date: '2026-01-29' },
        fumigation: { status: 'Approved', uploaded_by: 'QC Team', date: '2026-01-30' },
      },
    },
    {
      order_no: 'EX-110',
      customer_id: 2,
      country: 'SAUDI ARABIA',
      product_id: 1,
      product_name: '1121 Basmati Brown Rice',
      qty_mt: 15,
      price_per_mt: 650,
      currency: 'USD',
      contract_value: 9750,
      incoterm: 'FOB',
      advance_pct: 30,
      advance_expected: 2925,
      advance_received: 2925,
      advance_date: '2026-03-10',
      balance_expected: 6825,
      balance_received: 0,
      balance_date: null,
      status: 'Advance Received',
      current_step: 2,
      shipment_eta: '2026-05-10',
      source: 'Internal Mill',
      vessel_name: null,
      booking_no: null,
      etd: null,
      atd: null,
      eta: null,
      ata: null,
      destination_port: 'Jeddah, Saudi Arabia',
      created_at: '2026-03-01',
      costs: { rice: 0, bags: 0, loading: 0, clearing: 0, freight: 0, misc: 0 },
      documents: {
        phyto: { status: 'Pending', uploaded_by: null, date: null },
        blDraft: { status: 'Pending', uploaded_by: null, date: null },
        blFinal: { status: 'Pending', uploaded_by: null, date: null },
        invoice: { status: 'Pending', uploaded_by: null, date: null },
        packingList: { status: 'Pending', uploaded_by: null, date: null },
        coo: { status: 'Pending', uploaded_by: null, date: null },
        fumigation: { status: 'Pending', uploaded_by: null, date: null },
      },
    },
  ];

  // Doc type key mapping for readable column names
  const docTypeMap = {
    phyto: 'Phytosanitary Certificate',
    blDraft: 'BL Draft',
    blFinal: 'BL Final',
    invoice: 'Commercial Invoice',
    packingList: 'Packing List',
    coo: 'Certificate of Origin',
    fumigation: 'Fumigation Certificate',
  };

  for (const order of orders) {
    const { costs, documents, created_at, ...orderData } = order;

    // Insert the order and get the auto-generated id
    const [inserted] = await knex('export_orders')
      .insert({ ...orderData, created_at })
      .returning('id');
    const orderId = typeof inserted === 'object' ? inserted.id : inserted;

    // Insert cost entries
    const costRows = Object.entries(costs).map(([category, amount]) => ({
      order_id: orderId,
      category,
      amount,
    }));
    if (costRows.length > 0) {
      await knex('export_order_costs').insert(costRows);
    }

    // Insert document entries
    const docRows = Object.entries(documents).map(([key, doc]) => ({
      order_id: orderId,
      doc_type: docTypeMap[key] || key,
      status: doc.status,
      uploaded_by: doc.uploaded_by || null,
      upload_date: doc.date || null,
    }));
    if (docRows.length > 0) {
      await knex('export_order_documents').insert(docRows);
    }

    // Insert status history entry for creation
    await knex('export_order_status_history').insert({
      order_id: orderId,
      from_status: null,
      to_status: orderData.status,
      changed_by: adminId, // admin
      reason: 'Order created (seed)',
      created_at: created_at || new Date().toISOString(),
    });
  }
};
