import api from '../../../api/client';
export const inventoryApi = {
  list: (params) => api.get('/api/inventory', params),
  summary: () => api.get('/api/inventory/summary'),
  getLot: (id) => api.get(`/api/inventory/lots/${id}`),
  getMovements: (lotId) => api.get(`/api/inventory/lots/${lotId}/movements`),
  createLot: (data) => api.post('/api/inventory/lots', data),
  adjustStock: (data) => api.post('/api/inventory/adjust', data),
  reserveStock: (data) => api.post('/api/inventory/reserve', data),
  releaseReservation: (id) => api.post(`/api/inventory/release/${id}`),
};
export const lotInventoryApi = {
  listLots: (params) => api.get('/api/lot-inventory/lots', params),
  getLot: (id) => api.get(`/api/lot-inventory/lots/${id}`),
  getLotTransactions: (id) => api.get(`/api/lot-inventory/lots/${id}/transactions`),
  createPurchaseLot: (data) => api.post('/api/lot-inventory/lots/purchase', data),
  recordTransaction: (lotId, data) => api.post(`/api/lot-inventory/lots/${lotId}/transactions`, data),
  updateLotCosts: (id, data) => api.put(`/api/lot-inventory/lots/${id}/costs`, data),
  stockReport: (params) => api.get('/api/lot-inventory/reports/stock', params),
  getLotAncestry: (id) => api.get(`/api/lot-inventory/lots/${id}/ancestry`),
  getLotDescendants: (id) => api.get(`/api/lot-inventory/lots/${id}/descendants`),
  getBatchTrace: (batchId) => api.get(`/api/lot-inventory/batch-trace/${batchId}`),
  getOrderTrace: (orderId) => api.get(`/api/lot-inventory/order-trace/${orderId}`),
  getOrderCOGS: (orderId) => api.get(`/api/lot-inventory/order-cogs/${orderId}`),
  listAdjustments: (params) => api.get('/api/lot-inventory/adjustments', params),
  createAdjustment: (data) => api.post('/api/lot-inventory/adjustments', data),
  approveAdjustment: (id) => api.put(`/api/lot-inventory/adjustments/${id}/approve`),
  rejectAdjustment: (id, data) => api.put(`/api/lot-inventory/adjustments/${id}/reject`, data),
  getReconciliation: () => api.get('/api/lot-inventory/reconciliation'),
  getLotReconciliation: (id) => api.get(`/api/lot-inventory/reconciliation/${id}`),
  takeValuationSnapshot: () => api.post('/api/lot-inventory/valuation-snapshot'),
  getValuationHistory: () => api.get('/api/lot-inventory/valuation-history'),
  getDataProblems: () => api.get('/api/lot-inventory/data-problems'),
  repairLotCost: (id, data) => api.post(`/api/lot-inventory/repair-lot-cost/${id}`, data),
  getRepairLog: () => api.get('/api/lot-inventory/repair-log'),
};
